# -*- coding: utf-8 -*-
"""Breast_Cancer_classification _using_NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M4Qno8cnJhJxuk01eYXqGI0KUw3D2KCb
"""

d

import numpy as np
import pandas as pd
import keras as ke
import sklearn.datasets

breast_cancer_dataset=sklearn.datasets.load_breast_cancer()

print(breast_cancer_dataset)

df=pd.DataFrame(breast_cancer_dataset.data,columns=breast_cancer_dataset.feature_names)

df['Label']=breast_cancer_dataset.target

df

df.info()

df.isnull().sum()

df.describe()

df.head()

df.tail()



benign_count = df['Label'].value_counts()[0]
benign_count

malignant_count = df['Label'].value_counts()[1]
malignant_count

from sklearn.model_selection import train_test_split
x=df.iloc[0:,:30]
y = df['Label']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
s=StandardScaler()
m=s.fit_transform(X_train)
m

m_=s.fit_transform(X_test)
m_

import tensorflow as tf
from tensorflow import keras

model=keras.Sequential([
    keras.layers.Dense(20, activation ='relu', input_shape=(30,)),
    keras.layers.Dense(2, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

h=model.fit(m,y_train,epochs=32,validation_split=0.2)

x=h.history['accuracy']
y=h.history['val_accuracy']
plt.plot(x)
plt.plot(y)
plt.show()

import matplotlib.pyplot as plt

x=h.history['loss']
y=h.history['val_loss']
plt.plot(x)
plt.plot(y)
plt.show()
plt.show()

